AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AWS Lambda Proxy Resources

Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Timeout: 600
    Tracing: Active
    Architectures: ["arm64"]
    Runtime: provided.al2
    Handler: bootstrap.main
    CodeUri: .

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: Name of the APIG Stage
  ProxyApiKey:
    Type: String
    Description: The API key to authorize incoming requests
  TargetHost:
    Type: String
    Default: ""
    Description: The default target host to forward requests to if the `X-Target-Host` header is not provided.


Resources:
  ProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
      Environment:
        Variables:
          API_KEY: !Ref ProxyApiKey
          TARGET_HOST: !Ref TargetHost
    Metadata:
      BuildMethod: makefile
  
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - OPTIONS
          - GET
          - POST
          - PUT
          - DELETE
        AllowHeaders:
          - '*'
        MaxAge: 3600

  
Outputs:
  HttpApiUrl:
    Description: URL of the proxy endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
